### ISSUE TITLE
choose utility methods, model of the property includes a custom object will prompt error

### ISSUE THREAD

**Issue by JavenZ** [Ahmed-Ali/JSONExport#53] opened 2016-09-12 07:45 UTC
like this：
no visible @interface for 'testLastValue' declares the selector 'copyWithZone:'

**Comment by Ahmed-Ali** [comment] 2016-09-12 08:50
Hi @JavenZ 
can you please give an example JSON object and steps to reproduce?

**Comment by JavenZ** [comment] 2016-09-12 09:10
```
{
      "code" : "e21",
      "lastValue" : {
        "value" : 122,
        "date" : "2016-08-22",
        "cycleCount" : 0
      },
      "multiply" : 1,
      "name" : "123",
      "position" : null,
      "uuid" : "2c918c8b56fc42750156ff0885920037"
    }
```
just paste this json string, and all by default.

<img width="1054" alt="2016-09-12 16 59 48" src="https://cloud.githubusercontent.com/assets/17868438/18430277/5f68d966-790a-11e6-9b48-b35fd2aa6d84.png">

import the object ,  the project prompt error
<img width="561" alt="2016-09-12 17 05 08" src="https://cloud.githubusercontent.com/assets/17868438/18430489/5137637a-790b-11e6-8c87-916a09338f14.png">

write <NSCopying> on interface , the error disappear.
@interface ReadingJELastValue : NSObject<NSCopying>

May be I used the wrong way? please forgive my poor English :P
[归档.zip](https://github.com/Ahmed-Ali/JSONExport/files/466937/default.zip)

**Comment by Ahmed-Ali** [comment] 2016-09-12 09:18
No you are not using it in the wrong way. The exported file should call the "copy" method instead of "copyWithZone:". You can modify the files manually for now. I will get this fixed in the next release.

Thanks for reporting it!

**Comment by JavenZ** [comment] 2016-09-12 09:48
: )

**Comment by Ahmed-Ali** [comment] 2016-09-25 12:52
The problem is now solved in the develop branch and will be merged in the master branch soon

**Closed by Ahmed-Ali** 2016-09-25 12:52 UTC
