### ISSUE TITLE
Java- String array issue

### ISSUE THREAD

**Issue by falcon2010** [Ahmed-Ali/JSONExport#6] opened 2015-02-12 15:40 UTC
If model class  have JSONArray  the output of generation be like : 
need to convert the  JSONArray to String [] array
      
           jsonObject.optString[]("jsonarrayData");

**Comment by Ahmed-Ali** [comment] 2015-03-02 02:07
I saw this issue my self, but could not reproduce it again. Though, added some additional checks to avoid it. Should be fixed now.

**Closed by Ahmed-Ali** 2015-03-02 02:07 UTC
