### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by axaiOS** [Ahmed-Ali/JSONExport#22] opened 2015-09-15 16:01 UTC
This Json generates wrong (non-working) output with Objective C - iOS:

```javascript
[
  {
    "timezone": "Europe/Vienna",
    "spatial_features": [
      [
        16.31,
        48.18
      ]
    ],
    "met_sets": [
      {
        "name": "basic_now",
        "begin": "2015-09-15T16:08:00+02:00",
        "parameter_timesets": [
          {
            "params": [
              "TEMP_FELT",
              "WIND_GUST",
              "TEMP",
              "CC",
              "HUM_REL",
              "PREC",
              "WIND_DIR",
              "SYM_W",
              "WIND",
              "PRES_MSL"
            ],
            "timebase": "NOW",
            "data": [
              [
                [
                  293.6
                ],
                [
                  9.222
                ],
                [
                  293.1
                ],
                [
                  0.8415
                ],
                [
                  0.7104
                ],
                [
                  0.0
                ],
                [
                  3.067
                ],
                [
                  5
                ],
                [
                  4.039
                ],
                [
                  101051.0
                ]
              ]
            ]
          }
        ]
      }
    ]
  }
]
```

Specifically it generates:
```
#import "NSArray.h"
```
and
```
    for(NSDictionary * dataDictionary in dataDictionaries){
			NSArray * dataItem = [[NSArray alloc] initWithDictionary:dataDictionary];
			[dataItems addObject:dataItem];
		}
```

**Comment by Ahmed-Ali** [comment] 2015-09-28 21:01
First off, sorry for the late reply, but things are going little bit messy these days :)
Second, the issue is reproducible; I will fix it as soon as possible.

**Comment by Ahmed-Ali** [comment] 2015-12-29 20:28
The fix require changes in many places; and my time does not have enough space for it right now.
And the issue has been marked as a limitation for the app for now, and Readme file has been updated.

**Closed by Ahmed-Ali** 2015-12-29 20:28 UTC
