### ISSUE TITLE
Java-Model space in setter and getter methods

### ISSUE THREAD

**Issue by falcon2010** [Ahmed-Ali/JSONExport#5] opened 2015-02-12 15:34 UTC
when generate code for java class found space in the method name  

    public void set Productid(int productId) {
        this.productId = productId;
    }

    public int get Productid() {
        return this.productId;
    }

**Comment by Ahmed-Ali** [comment] 2015-03-02 02:08
I saw this issue my self, but could not reproduce it again. Though, added some additional checks to avoid it. Should be fixed now.

**Closed by Ahmed-Ali** 2015-03-02 02:08 UTC
